### PR TITLE
Alan testing

### PR DESCRIPTION
**Pull request by alan24**
I put this pull request in because the coordinate (0, 0) was not at the bottom left, so I think I fixed this issue. This is up to the team if y'all want to change the code to have (0,0) on the bottom left. 
I ran some tests on coordinates to see if correct pieces populated on the board on the correct coordinates. 

Edit: Don't merge this file.

### CODE REVIEW

**Comment by KaoruDev** [comment]
:+1: let's get everyone's ok before merging this since we're essentially have to think backwards / or forward however you like to currently think of it haha

**Comment by alan24** [comment]
I don't plan to merge this pull request. I just put it here if our team wants it this way.
I am trying to remove this pull request lol.

**Comment by KaoruDev** [comment]
I'm cool with it, i think it's a good practice because it'll create tons of bugs for you folks to fix  muahahaha

**Comment by alan24** [comment]
I thought you liked the top to bottom and top to bottom because the app will be easier to build on the front end using HTML/CSS and jQuery.

**Comment by KaoruDev** [comment]
yes, but i'm just one person, let alone someone who doesn't have to wrestle with the code on a daily. Team opinion > than mine =)

**Comment by alan24** [comment]
I don't think all the team members replied on this issue, so I will not merge this pull request until everyone has an opinion on this =)

**Comment by KaoruDev** [comment]
:+1:

**Comment by JohannBillar** [comment]
Probably better to keep it as is for now. =) Or have a vote on Slack.

**Pull request closed without merging**
